language: cpp

os:
  - linux

compiler:
    - clang
    - gcc

addons:
  apt:
    - cmake
    - cmake-data

before_install:
    - pip install --user cpp-coveralls

script:
- cmake -H. -B_build -DBUILD_TESTS=ON
- cmake --build _build
- cmake --build _build --target test -- ARGS=--verbose

after_success:
- coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
